services:
  mysql:
    container_name: mysql-lawmon
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mysql-lawmon
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 5s
      retries: 10
      start_period: 30s
      timeout: 5s
    networks:
      - app-network

  redis:
    container_name: redis-lawmon
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - db_redis:/data
    restart: always
    networks:
      - app-network

volumes:
  db_mysql:
  db_redis:

networks:
  app-network:
    external: true