{
 "title": "Lawmon Dashboard",
 "tags": [ "lawmon" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP 요청 수",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "5xx 에러 비율",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m])) / sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "5xx 비율"
    }
   ]
  },
  {
   "title": "컨테이너별 CPU 사용량",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "MySQL 쿼리 응답 속도",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[1m])",
     "legendFormat": "쿼리 응답 수"
    }
   ]
  }
 ]
}